#!/bin/bash
module load vasp/5.4.1

cd /afs/crc.nd.edu/user/j/jcrum/Chabazite/protonation/methylene/isolated/carbene
cd /afs/crc.nd.edu/user/j/jcrum/Chabazite/protonation/methylene/isolated/carbene/carbene/relax  # this is the vasp directory

runvasp.py     # this is the vasp command
#end
