#!/bin/bash
module load vasp/5.4.1

cd /afs/crc.nd.edu/user/j/jcrum/Chabazite/protonation/methylene/isolated
cd /afs/crc.nd.edu/user/j/jcrum/Chabazite/protonation/methylene/isolated/D-46/DISP  # this is the vasp directory

runvasp.py     # this is the vasp command
#end
